### ISSUE TITLE
CommandBus setup

### ISSUE THREAD

**Issue by AlbertMorenoDEV** [thephpleague/tactician-bundle#37]
Hi,

I'm trying to use tactician-bundle in a Symfony 3 project.
I've installed through composer.
Then I've added bundle in the kernel class.

Maybe I left some config step?

When I try to get command bus in the controller with $this->get('tactician.commandbus') I'm getting an error, It doesn't exist.

I've tried to add manually in my services.yml, but I need to setup each middleware.
Are this the correct path?

Thanks a lot,

Albert

**Comment by rosstuck** [comment]
Hi Albert,

Sorry to hear you're having problems! Can you let me know which version of
Tactician you're using and the exact error message you're seeing? That
would help a lot.

There is usually some config to place inside config.yml, you can see some
examples here:
https://github.com/thephpleague/tactician-bundle/blob/master/README.md#configuring-middleware

Thanks in advance and sorry for the issues :)


On Feb 8, 2017 10:50 PM, "Albert Moreno" <notifications@github.com> wrote:

Hi,

I'm trying to use tactician-bundle in a Symfony 3 project.
I've installed through composer.
Then I've added bundle in the kernel class.

Maybe I left some config step?

When I try to get command bus in the controller with
$this->get('tactician.commandbus') I'm getting an error, It doesn't exist.

I've tried to add manually in my services.yml, but I need to setup each
middleware.
Are this the correct path?

Thanks a lot,

Albert

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/thephpleague/tactician-bundle/issues/37>, or mute the
thread

**Comment by AlbertMorenoDEV** [comment]
Hi,

I'm in v1.0.2.

Now, trying to get last error to post it here, I got an other error, non related with tactician.
Now tactician.commandbus it seems to exist.

Sorry for disturb and thanks
