### ISSUE TITLE
One handler for all commands (in v0.4.1)

### ISSUE THREAD

**Issue by miguelrs** [thephpleague/tactician-bundle#86]
I'm trying to introduce Tactician in a Symfony project, but I need to stick to v0.4.1, as I'm on PHP 5.5 😞 

For reasons I'm not going to explain in detail, I need to create a command bus whose handler handles all the existing commands...  
In `master` branch, I think you can do that [by adding a custom `HandlerMapping`](https://github.com/thephpleague/tactician-bundle#3-custom-mapping-rules), but in `0.4.1` I can't see that...  

Is there any approach I can use?  
And if not, would it be possible to add that functionality to 0.4.1 (I don't think PHP 7 is required for that, is it)?

**Comment by miguelrs** [comment]
Actually, looking at it, I think I just need create a custom Locator, and then define my own command handler service, where I can inject my locator, and use that as the last middleware parameter for my bus... 👌

**Comment by rosstuck** [comment]
Hi Miguel,

Quick answer because I'm at lunch but you can just define your own
middleware and put it at the end of the chain. That'll be easier than
defining your own locator etc. :)

On Nov 13, 2017 12:34 PM, "Miguel Rosales" <notifications@github.com> wrote:

Closed #86 <https://github.com/thephpleague/tactician-bundle/issues/86>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/thephpleague/tactician-bundle/issues/86#event-1338510060>,
or mute the thread
